### ISSUE TITLE
RuntimeError: No matching overloads found. at native/common/jp_method.cpp:117

### ISSUE THREAD

**Issue by jialeiwang** [ibmdbanalytics/ibmdbpy#18]
I got this error when calling ```IdaDataBase(connection_string)```. I noticed that in file ```base.py``` line 284, ```self._connection_string``` is a Python list, and the subsequent call ```jaydebeapi.connect()``` raises error when reading ```self._connection_string``` as a list. My solution is to change ```self._connection_string``` to a string, in the format of ```'jdbc:db2://<HOST>:<PORT>/<DBNAME>:user=<UID>;password=<PWD>'```, and it works.

I encountered this error in Mac OS, Python 3.6, ibmdbpy version 0.1.4, JayDeBeApi 1.0.0, jpype 0.6.2, jdk 1.8. I wonder whether this is a bug, or there is the right way to resolve this?

**Comment by nicoleschoen** [comment]
hi jialeiwang,
thanks for reporting this issue. Looks like this is due to a change in the JayDeBeApi from version 0.2.0 to 1.0.0 . The current implementation works fine with the previous version (0.2.0), but I can reproduce the issue with version 1.0.0.
Thanks for providing a workaround until we fix it in the package.

**Comment by petemarshall77** [comment]
Thanks for the workaround. I needed to add a final semicolon after the password in the connection string for this to work for me (connecting to dashDB).

**Comment by mineo** [comment]
This has been fixed a while ago by #32.
